#!/bin/tcsh
module load java-tig
module unload ant
module unload ant-tig

setenv ANT_HOME /usr/share/ant

java -agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y -classpath ${ANT_HOME}/lib/ant-launcher.jar -Dant.home=${ANT_HOME} -Dant.library.dir=${ANT_HOME}/lib org.apache.tools.ant.launch.Launcher -cp "" -Dsource=phytozome-chado-B.distachyon-early-release
