#!/bin/sh

export INIT=/software/noarch/local/init
. $INIT/bash/common.bashrc

cd ~/svn/trunk
svn up
cd imbuild/javadoc
ant

chmod -R a+rX build/javadoc/
rsync -av --delete build/javadoc/ flymine@www.flymine.org:/var/www/intermine/api/
