#!/bin/sh

export INIT=/software/noarch/local/init
. $INIT/bash/common.bashrc

cd ~/svn/trunk
svn up

cd ~/svn/trunk/bio/test-all/dbmodel
ant clean-all
ant build-db

cd ~/svn/trunk/imbuild/javadoc
ant
chmod -R a+rX build/javadoc/
rsync -avc --delete build/javadoc/ flymine@www.flymine.org:/var/www/html/api/
