#!/bin/sh

# This will make a release of FlyMine

usage="Usage: $0 <nightly/official> <version>"

if [ $# -lt 1 ]
then
    echo $usage
    exit 1
fi

server=flymine@download.flymine.org
apiserver=flymine@www.flymine.org
tempdir=/tmp/flymine-release-$$

apidir=/var/www/flymine/http/api
destdirbase=/chroot/download

if [ $1 == "nightly" ]
then
    destdir=$destdirbase/nightly
    version=`date +%Y%m%d`
else
    destdir=$destdirbase/releases
    version="noversion"
fi

if [ $# -eq 2 ]
then
    version=$2
fi

echo "Releasing $1 version $version of FlyMine"

### Make a temporary directory
mkdir $tempdir

### Checkout a clean version of FlyMine

cd $tempdir
now=`date +"%d %b %Y %H:%M"`
echo "Date is $now"
command="svn export svn://svn.flymine.org/flymine/trunk/flymine flymine-$version"
eval $command


## Create the tarred source files from the clean checkout
tar czvf flymine-src-$version.tar.gz flymine-$version
zip -r flymine-src-$version.zip flymine-$version

### Release javadoc
#if [ $1 == "nightly" ]
#then
#    cd $tempdir/flymine-$version
#    ant dist-javadoc

#    command="ssh $apiserver \"rm -rf $apidir/*\""
#    eval $command

#    command="scp -r dist/api/* $apiserver:$apidir/"
#    eval $command

#    command="ssh $apiserver \"find $apidir -type f | xargs chmod a+r\""
#    eval $command
#    command="ssh $apiserver \"find $apidir -type d | xargs chmod a+rx\""
#    eval $command
#fi

### Remove releases older than 7 days
if [ $1 == "nightly" ]
then
    command="ssh $server \"find $destdir -mtime +7 -name \"flymine*.*\" | xargs rm -f\""
    eval $command
fi

### Copy the source archives to the destination
command="scp *.tar.gz *.zip $server:$destdir/"
eval $command

### Make sure all permissions are world-readable
command="ssh $server \"find $destdir -type f -name \"flymine*.*\"| xargs chmod a+r\""
eval $command

cd $origdir
rm -rf $tempdir
