#!/usr/bin/python

import os, urllib, tarfile
from BeautifulSoup import BeautifulSoup

organisms = ['7227', '6239', '4932']

#os.mkdir("tmp")
#urllib.urlretrieve('http://www.thebiogrid.org/downloads/datasets/organisms.tar.gz', 'tmp/organisms.tar.gz')

newdir = 'version_1'


if not os.path.exists(newdir):
   os.mkdir(newdir)

tar = tarfile.open("tmp/organisms.tar.gz", "r:gz")
for tarinfo in tar:
    for taxon in organisms:
        if taxon + '.psi25.xml' in tarinfo.name:
            print 'extracting: ' + tarinfo.name
            tar.extract(tarinfo.name, newdir)


os.symlink(newdir, 'current')

tar.close()
