#!/bin/sh

# This will make a release of InterMine

usage="Usage: $0 <nightly/official> <version>"

if [ $# -lt 1 ]
then
    echo $usage
    exit 1
fi

server=flymine@download.flymine.org
apiserver=flymine@www.flymine.org
tempdir=/tmp/intermine-release-$$

apidir=/var/www/intermine/api
destdirbase=/chroot/download

if [ $1 == "nightly" ]
then
    destdir=$destdirbase/nightly
    version=`date +%Y%m%d`
else
    destdir=$destdirbase/releases
    version="noversion"
fi

if [ $# -eq 2 ]
then
    version=$2
fi

echo "Releasing $1 version $version of InterMine"

### Make a temporary directory
mkdir $tempdir

### Checkout a clean version of InterMine

cd $tempdir
now=`date +"%d %b %Y %H:%M"`
#echo "Date is $now"
command="svn export svn://subversion.flymine.org/trunk intermine-$version"
eval $command

command="rm -rf $tempdir/intermine-$version/flymine"
eval $command

## Create the tarred source files from the clean checkout
tar czvf intermine-src-$version.tar.gz intermine-$version
zip -r intermine-src-$version.zip intermine-$version

### Build the tutorial
cd $tempdir/intermine-$version
ant build-tutorial

cd $tempdir
# no longer create tutorial
#mv intermine-$version/build/tutorial intermine-tutorial-$version
#tar czvf intermine-tutorial-$version.tar.gz intermine-tutorial-$version
#zip -r intermine-tutorial-$version.zip intermine-tutorial-$version

### Release javadoc
if [ $1 == "nightly" ]
then
    cd $tempdir/intermine-$version/imbuild/javadoc
    ant

    command="ssh $apiserver \"rm -rf $apidir/*\""
    eval $command

    command="scp -r build/javadoc/* $apiserver:$apidir/"
    eval $command

    command="ssh $apiserver \"find $apidir -type f | xargs chmod a+r\""
    eval $command
    command="ssh $apiserver \"find $apidir -type d | xargs chmod a+rx\""
    eval $command
fi


### Remove releases older than 7 days
if [ $1 == "nightly" ]
then
    command="ssh $server \"find $destdir -mtime +7 -name \"intermine*.*\" | xargs rm -f\""
    eval $command
fi

cd $tempdir
### Copy the source archives to the destination
command="scp *.tar.gz *.zip $server:$destdir/"
eval $command

### Make sure all permissions are world-readable
command="ssh $server \"find $destdir -type f -name \"intermine*.*\" | xargs chmod a+r\""
eval $command

cd $origdir
rm -rf $tempdir
