#!/usr/bin/perl

use strict;
use warnings;
use Carp;
use Storable;
use File::Basename;
use SVG::TT::Graph::Line;

my $data_file = dirname($ENV{SCRIPT_FILENAME}).'/../cached_data/analytics';
my $data      = retrieve($data_file);
my $title     = 'Template Analytics Graph';

my @dates = sort keys %$data;
my %line_names;
for my $d (@dates) {
    $line_names{$_}++ for (keys %{$data->{$d}});
}
my %line_for;
for my $ln (keys %line_names) {
    for my $d (@dates) {
	push(@{$line_for{$ln}}, $data->{$d}{$ln} || 0);
    }
}

my $graph = SVG::TT::Graph::Line->new({
				       'fields' => \@dates,
				       area_fill => 0,
				       rotate_x_labels => 1,
				       random_colors => 1,
				       scale_integers => 1,
				       key => 1,
				       tidy => 0,
				      });
$graph->compress(0);
for (keys %line_names) {
    $graph->add_data({
		      'data'  => \@{$line_for{$_}},
		      'title' => $_,
		     });
}
print "Content-type: image/svg+xml\n\n";
print $graph->burn();
# open(SVG, '<', '/tmp/out.svg') or croak "$!";
# while (<SVG>) {
#     print;
# }
#print  "Content-type: text/plain\n\n";
#print "Ain't working right now - please check back later";
exit;
