#!/bin/sh
/usr/bin/which mvn > /dev/null
if [ $? -ne 0 ]
then
    echo "Maven2 (mvn) cannot be found on your PATH."
    exit 1
fi

VERSION=1.4.0.2
mvn install:install-file -DgroupId=com.jgraph -DartifactId=jgraphx -Dversion=${VERSION} -Dpackaging=jar -Dfile=jgraphx-${VERSION}.jar -DgeneratePom=true -DcreateChecksum=true
mvn install:install-file -DgroupId=com.jgraph -DartifactId=jgraphx -Dversion=${VERSION} -Dpackaging=jar -Dfile=jgraphx-${VERSION}-sources.jar -Dclassifier=sources -DcreateChecksum=true
