#!/bin/sh

# Script to mirror an ensembl database

DBHOST=localhost
DBUSER=flymine
DBPASSWD=getmydata

##################################################################################################

if [[ $# < 1 ]]; then
    echo "Usage: $0 <organism>"
    exit 1
fi

ORGANISM=$1
REMOTE_LOCATION=ftp://ftp.ensembl.org/pub/current_${ORGANISM}/data/mysql/\*core\*
TMPDIR=ensembl-${ORGANISM}-$$

##################################################################################################

dir=`pwd`

echo "--- Creating a directory for download (${TMPDIR})..."

mkdir $TMPDIR
cd $TMPDIR

echo -- Working out version
wget -nr --cut-dirs=4 -nH -l 1 "$REMOTE_LOCATION"

SOURCE_VERSION=`cat .listing |awk '/core/ {print $9}'|sed 's/^[^0-9]*_//'`

echo "Source version is $SOURCE_VERSION"

# See whether we have this database on the server
DBNAME="ensembl-${ORGANISM}-${SOURCE_VERSION}"
CURRENT_VERSION=`mysql -h$DBHOST -u$DBUSER -p$DBPASSWD mysql -e "show databases"| awk "/${DBNAME}/ {print}"`

if [ "$CURRENT_VERSION" = "" ]; then

    echo --- Downloading the latest version...
    wget -r -nd "$REMOTE_LOCATION"


    echo --- Checking...
    if ! gunzip -t *.gz
	then
	echo One or more files are corrupted
	exit 1
    fi

    echo --- Creating DB...$DBNAME
    if ! mysqladmin -h$DBHOST -u$DBUSER -p$DBPASSWD create $DBNAME
	then
	echo Unable to create the database $DBNAME
	exit 1
    fi

    echo --- Adding user rights
    mysql -h$DBHOST -u$DBUSER -p$DBPASSWD mysql -e "INSERT INTO db VALUES('$DBHOST','$DBNAME','$DBUSER','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y')"
    mysqladmin -h$DBHOST -u$DBUSER -p$DBPASSWD reload

    echo --- Uncompressing...
    gunzip *.gz

    echo --- Running table creation scripts...
    for sqlfile in *.sql
      do
      gunzip $sqlfile
      cat $sqlfile | mysql -h$DBHOST -u$DBUSER -p$DBPASSWD $DBNAME
    done

    echo --- Importing data...
    mysqlimport --local -h$DBHOST -u$DBUSER -p$DBPASSWD $DBNAME *.txt.table

    echo --- Completed.

else
    echo "Mirrored database is up to date"
fi

cd $dir
rm -r $TMPDIR

