#!/bin/sh

FILE=gadfly.tar.gz
DBHOST=localhost
DBUSER=gadfly_dba
DBPASSWD=123qwe

echo --- Downloading the latest version...
#rm -f $FILE
rm -rf gadfly/
#wget http://www.fruitfly.org/~cjm/mysql/$FILE

echo --- Checking...
if ! gunzip -t $FILE
then
    echo $FILE is corrupted
    exit 1
fi

echo --- Uncompressing...
tar zxf $FILE

DBNAME="gadfly-"`stat -t gadfly | awk '{print strftime("%Y%m%d",$13);}'`

echo --- Creating DB...
if ! mysqladmin -h$DBHOST -u$DBUSER -p$DBPASSWD create $DBNAME
then
   echo Unable to create the database $DBNAME
fi

echo --- Adding user rights
mysql -h$DBHOST -u$DBUSER -p$DBPASSWD mysql -e "INSERT INTO db VALUES('$DBHOST','$DBNAME','$DBUSER','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y')"
mysqladmin -h$DBHOST -u$DBUSER -p$DBPASSWD reload


echo --- Importing data...
cd gadfly
cat *.sql | mysql -h$DBHOST -u$DBUSER -p$DBPASSWD $DBNAME
mysqlimport --local -h$DBHOST -u$DBUSER -p$DBPASSWD $DBNAME *.txt

rm -r gadfly/

echo --- Completed.

