<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>

<div class="heading2">
Current Data
</div>
<div class="body">
<UL>
<LI><I>D. melanogaster</I> 3-D structural domain predictions<BR>
<p>
A set of 3-D structural domain predictions for D. melanogaster proteins generated by <A HREF="http://www-cryst.bioc.cam.ac.uk/~kenji/NEW/index.htm">Kenji Mizuguchi</A> are available.<BR>
3-D structural predictions were calculated for regions of the <I>D. melanogaster</I> release 3.1 peptides to which an <A href="http://www.ebi.ac.uk/interpro">interpro</A> domain assignment had been made (only <A href="http://www.sanger.ac.uk/Software/Pfam">PFam</A> domains were taken).  Stuctural data for each of these fragments is available in FlyMine. Currently the atomic coordinates for each structure together with a sequence-structure compatibility score (z-score) and a q-score are available.  The <A HREF="http://www.jmol.org">JMol structural viewer</A> has been integrated into FlyMine and allows viewing and further analysis of each domain structure. In the future the sequence-structure alignments will also be loaded.
</p>
</UL>
</DIV>

