=pod

=head1 NAME

Webservice::InterMine::Cookbook::Templates::Recipe2 - Logging in to access your templates

=head1 SYNOPSIS

  use Webservice::InterMine ('www.flymine.org/query/service', $user, $pass);

  ## Run your super secret private template gene -> cure for cancer
  my $template = Webservice::InterMine->template('Gene_To_Cure_For_Cancer');
      or die "Could not find template";

  my $results  = $template->results_with(value1 => 'Drosophila melanogaster');

=head1 DESCRIPTION

As long as you have provided your login
information to the service, you will be able to access your saved
templates and lists.

The template can be accessed and used as any other template,
both via the API and through the webapp. Don't forget that you can manage your
templates through the webapp interface, which in many cases might be more
straightforward than using this programmatic API.

=head1 CONCLUSION

If you have set up templates in a webapp, you can access them anywhere by using your login
details.

=cut
