#!/usr/bin/perl

use strict;
use warnings;
use Cwd;

my $home = $ENV{HOME};

my $script_dir = getcwd;

my $desktop_template = join('', <DATA>);
my $desktop_entry = eval $desktop_template;

my $desktop_file_location = $home . '/Desktop/MineManager.desktop';
open(my $desktop_file, '>', $desktop_file_location)
    or die "horribly $!";
print $desktop_file $desktop_entry;
close $desktop_file;

my $mode = 0755;
chmod $mode, $desktop_file_location;
exit;
# Note: for adding into the menu, the file should go to /usr/share/applications
__DATA__
qq![Desktop Entry]
Name=MineManager
Comment=Create and manage InterMine data warehouses
Comment[de]=InterMine Datenbanken anlegen und verwalten
Comment[it]=Creare ed amministrare banche dati di InterMine
Comment[es]=Construir y administrar bancos de datos de InterMine
GenericName=InterMine MineManager
GenericName[de]=InterMine Datenbankverwalter
GenericName[es]=Adminstrador de base de datos de InterMine
GenericName[it]=Sistemista di banche dati di InterMine
Exec=${script_dir}/run
Icon=${script_dir}/installer/src/main/resources/org/intermine/install/swing/intermine_logo_no_text.png
Type=Application
Categories=Development;Java
StartupNotify=true
Terminal=true!
