#!/usr/bin/env python

import sys
import xml.sax

import intermine.model
import itemxml.document
import itemxml.io

import book.handler

model_file = sys.argv[1]
book_xml = sys.argv[2]

model = intermine.model.Model(model_file)

item_factory = itemxml.document.Factory(model)
handler = book.handler.BookHandler(item_factory)
xml.sax.parse(book_xml, handler)

itemxml.io.write_itemsxml(item_factory)
