<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>

<div class="heading2">
  Current data
</div>
<div class="body">

      <dt>A set of 3-D structural domain predictions for <i>D. melanogaster</i>
      and <i>A. gambiae</i> proteins generated by
      <a href="http://www-cryst.bioc.cam.ac.uk/~kenji/NEW/index.htm">Kenji Mizuguchi</A>
      is available.<BR/> 

      <dt>3-D structural predictions were calculated for regions of
      the <I>D. melanogaster</I> release 3.1 peptides to which an
      <A href="http://www.ebi.ac.uk/interpro">interpro</A> domain assignment had been
      made (only <A href="http://www.sanger.ac.uk/Software/Pfam">PFam</A> domains
      were taken).  Stuctural data for each of these fragments is
      available in FlyMine. Currently the atomic coordinates for each
      structure together with a sequence-structure compatibility score
      (z-score) and a q-score are available. The <a href="http://www.jmol.org">JMol structural viewer</a> has been
      integrated into FlyMine and allows viewing and further analysis of each domain
      structure. In the future the sequence-structure alignments will also be
      loaded. 
    </dt>

</div>

