#!/bin/sh

# Container for cronjob

PATH=/usr/local/bin:/software/arch/postgresql/bin:$PATH
/software/noarch/bin/userprofile_backup -p 5433 /export/flymine/dumps/userprofile_backup gollum > $HOME/.userprofile_backup.output.new
if ! cmp $HOME/.userprofile_backup.output $HOME/.userprofile_backup.output.new
then
    cat $HOME/.userprofile_backup.output.new | mail kmr@flymine.org
fi 
