#!/bin/csh
wget -O /dev/stdout "http://zome-dev.phytozome.net/phytomine-dev/service/regions/sequence?query=%7B%22regions%22:[%22Chr01:10692566..10800215%22],%22featureTypes%22:[%22Exon%22],%22organism%22:%22210%22%7D"
