#!/usr/bin/env python

import sys
import os
import os.path
import xml.sax
from contextlib import closing

import codecs
import intermine.model
import itemxml.document
import itemxml.io

import book.handlers

model_file = sys.argv[1]
csv = sys.argv[2]
output = sys.argv[3]

model = intermine.model.Model(model_file)

item_factory = itemxml.document.Factory(model)
parser = book.handlers.BibliophileHandler(item_factory)
if os.environ.get('DEBUG'):
    parser.debug = True

with closing(codecs.open(csv, "r", "utf-8")) as src:
    parser.process(src)

try:
    with closing(open(output, 'w')) as out, itemxml.io.XMLWriter(out, allow_none = False) as writer:
        writer.write_items(item_factory)
except:
    os.remove(output)
    raise
