#!/usr/bin/env python

import sys
import os
import xml.sax

import intermine.model
import itemxml.document
import itemxml.io

import book.handler

model_file = sys.argv[1]
book_xml = sys.argv[2]
output = sys.argv[3]

model = intermine.model.Model(model_file)

item_factory = itemxml.document.Factory(model)
handler = book.handler.BookHandler(item_factory)
if os.environ.get('DEBUG'):
    handler.debug = True
xml.sax.parse(book_xml, handler)

itemxml.io.write_itemsxml(item_factory, output)
