#!/usr/bin/perl

use warnings;
use strict;

use InterMine::Model;
use InterMine::Item::Document;

if ( @ARGV != 4 ) {
    die "usage: $0 model_file kegg_map_title_file kegg_gene_map out_file\n";
}

my ( $model_file, $map_title_filename, $gene_map_filename, $outfile ) = @ARGV;

my $data_source = 'Kegg';
my $taxon_id    = 36329;

# The item factory needs the model so that it can check that new objects have
# valid classnames and fields
my $model = InterMine::Model->new( file => $model_file );

my $document = InterMine::Item::Document->new(
    model  => $model,
    output => $outfile,
);

# read the map title file into %pathways

...

# read the gene map file and create item objects

...

# write the items
$document->write();

exit;
