#!/usr/bin/perl

use warnings;
use strict;
use lib '/../intermine/perl/lib';

use XML::Writer;
use InterMine::Model;
use InterMine::ItemFactory;

if (@ARGV != 4) {
  die "usage: $0 model_file kegg_map_title_file kegg_gene_map out_file\n";
}

my ($model_file, $map_title_filename, $gene_map_filenamei, $outfile) = @ARGV;

my $data_source = 'Kegg';
my $taxon_id    = 36329;

# The item factory needs the model so that it can check that new objects have
# valid classnames and fields
my $model        = InterMine::Model->new(file => $model_file);
my $item_factory = InterMine::ItemFactory->new(model => $model);

my @items;

# read the map title file into %pathways

...

# read the gene map file and create item objects

...


# write the items
open(my $output, '>', $out_file) 
    or die "Cannot open $outfile for writing, $!";

my $writer = new XML::Writer(
    DATA_MODE   => 1, 
    DATA_INDENT => 3, 
    OUTPUT      => $output,
);

$writer->startTag("items");
for my $item (@items) {
    $item->as_xml($writer);
}
$writer->endTag("items");

close($output) or die "Cannot close $outfile, $!";
exit;
