#!/bin/bash

# The following environment variables need to be set
# INTERMINE: location of local InterMine installation

export INTERMINE=~/svn/trunk/intermine
export FLYMINE=~/svn/trunk/flymine
export BIO=~/svn/trunk/bio

CP=$CLASSPATH

#for i in $INTERMINE/lib/*.jar ; do
#    CP=$CP:$i
#done

#for i in $INTERMINE/dist/*.jar ; do
#    CP=$CP:$i
#done


CP=$CP:$INTERMINE/objectstore/main/dist/intermine-objectstore.jar
for i in $INTERMINE/objectstore/main/lib/*.jar ; do
    CP=$CP:$i
done
CP=$CP:$INTERMINE/web/main/dist/intermine-web.jar
CP=$CP:$INTERMINE/pathquery/main/dist/intermine-pathquery.jar
CP=$CP:$INTERMINE/web/model/userprofile/dist/userprofile.jar
for i in $INTERMINE/web/main/lib/*.jar ; do
    CP=$CP:$i
done
CP=$CP:$BIO/core/props/resources
CP=$CP:$BIO/webapp/resources
CP=$CP:~
CP=$CP:$FLYMINE/webapp/build/main
CP=$CP:$FLYMINE/dbmodel/build/classes
CP=$CP:$FLYMINE/dbmodel/resources

if test -z "$LD_LIBRARY_PATH" ; then
    export LD_LIBRARY_PATH=/usr/lib:/lib:/usr/lib/jni
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/lib:/usr/lib/jni
fi

echo "Using classpath: $CP"
echo "Using LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

java -cp $CP -Xmx1000M org.intermine.web.logic.PerformanceTester $*

