#!/usr/bin/perl

# for a mine name return the large version number of the existing properties files
# where the files are named like: <mine_name>.properties.r<number>

BEGIN {
  my $DIR = ($0 =~ m:(.*)/.*:)[0];
  push (@INC, $DIR . '/../../intermine/perl/lib');
}

use warnings;
use strict;

use InterMine::Util qw(get_latest_properties_version $INTERMINE_CONF_DIR);

sub usage
{
  my $message = shift;

  if (defined $message) {
    warn "$message\n\n";
  }

  die <<"USAGE";
$0 <mine_name>

return the most recent properties file version, eg. for:
foomine.properties.r1,
foomine.properties.r2,
foomine.properties.r3

print "3" to STDOUT
USAGE
}

if (@ARGV != 1) {
  usage('wrong number of arguments');
}

my $mine_name = shift;

my $prop_file_prefix = "$mine_name.properties.r";
my $version = get_latest_properties_version($prop_file_prefix);

print "$version\n";

