#!/usr/bin/perl
# script to download ncbi gene number and pubmed ID files

use strict;

BEGIN {
  # find the lib directory by looking at the path to this script
  push (@INC, ($0 =~ m:(.*)/.*:)[0] . '/../../intermine/perl/lib/');
}
use InterMine::DataDownloader;

#Define ARGVs
my ($logdir,$logname,$home,$config_file);
if(@ARGV!=4){
	die "Wrong number of ARGVs!\nget_all.sh should supply the log directory, temporary log name, /shared/data/ and config file.\n";
}else{
	$logdir = $ARGV[0];
	$logname= $ARGV[1];
	$home = $ARGV[2];
	$config_file = $ARGV[3];
}

print "\nReady to download NCBI gene and pubmed Id...\n";

#for connecting to the ftp server
my $ncbi_server = "ftp.ncbi.nlm.nih.gov";
my $ncbi_dir = "gene/DATA";
my $username = "anonymous";
my $password = "richard\@flymine.org";

#files to download
my $gene_info_file = "gene_info.gz";
my $pubmed_info_file = "gene2pubmed.gz";

#connect to the server and change to source directory
my $connection = &ftp_connect($ncbi_server,$username,$password);
	
$connection->cwd($ncbi_dir)
	or die "Cannot change working directory ", $connection->message;

#use the date stamp to create a version id for the output directory
my $date_string = &date_string_file($connection,$pubmed_info_file);

#destination directories
my $ncbi_main_dir = "$home/pubmed";
my $download_dir = "$ncbi_main_dir/$date_string";
my ($updated,$version_buffer,$log_buffer);

#make sure that the necessary directories exist and download new data if available
my $current_link = "$home/pubmed/current";
&checkdir_exists($ncbi_main_dir);
if(&checkdir_exists($download_dir)==1){
	&ftp_download($connection,$download_dir,$gene_info_file);
	&ftp_download($connection,$download_dir,$pubmed_info_file);
	&unzip_dir($download_dir);
	&make_link($date_string,$current_link);
	my $date = &convert_date();
	$log_buffer = "NCBI_Id_PubmedId\nNew data available in $download_dir containing file ";
	$version_buffer = "Gene versus publications from PubMed\n$date_string\nA mapping between genes and publications which mention them for D. melanogaster, C. elegans and S. cerevisiae  from NCBI\nhttp://www.ncbi.nlm.nih.gov/\n";
	$updated = 1;
}else{
	warn " current version up to date - skipping download\n";
	$log_buffer = "NCBI_Id_PubmedId\nCurrent data ok\n\n";
	$updated = 0;
}

$connection->quit;

# write log and version files
if($updated == 1){
#	$log_buffer .= "ncbiID_pubmedID.xml\n\n";
	&write_version($ncbi_main_dir,$version_buffer);
	system "chmod -R a+r,g+w $download_dir";
}
&write_log($log_buffer,$logdir,$logname);

