intermine.plugin.repo=file:///home/runner/intermine/plugin/build/libs
intermine.development.intermineRootDir=/home/runner/intermine/intermine
intermine.development.intermineModules=api,integrate,jbrowse-endpoint,model,objectstore,pathquery,resources,webapp,webtasks

intermine.development.bioRootDir=/home/runner/intermine/bio
intermine.development.bioModules=core,model,tools,webapp
