intermine.plugin.repo=file:///home/runner/work/intermine/intermine/plugin/build/libs
intermine.development.intermineRootDir=/home/runner/work/intermine/intermine/intermine
intermine.development.intermineModules=api,integrate,jbrowse-endpoint,model,objectstore,pathquery,resources,webapp,webtasks

intermine.development.bioRootDir=/home/runner/work/intermine/intermine/bio
intermine.development.bioModules=core,model,tools,webapp,postprocess/create-chromosome-locations
