<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="im" %>

<table width="100%">
  <tr>
    <td valign="top">
      <div class="heading2">
        Current data
      </div>
    </td>
    <td valign="top">
      <div class="heading2">
        Bulk download
      </div>
    </td>
  </tr>
  <tr>
    <td valign="top">
      <div class="body">
<%--
        <h4>
          <a href="javascript:toggleDiv('hiddenDiv1');">
            <img id='hiddenDiv1Toggle' src="images/disclosed.gif" title="Click here to view the datasets" />
            Major data sets ...
          </a>
        </h4>

        <div id="hiddenDiv1" class="dataSetDescription">
--%>
    <div>
      <p>
            <a href="/">modMine</a> is a resource aimed at the exploration of the data generated by the modENCODE project.
            <p>modENCODE aims to identify all functional elements in the genomes of the fruit fly (Drosophila melanogaster) 
            and the worm (Caenorhabditis elegans).
          </p>
         <ul>
         <li>
              <i>Drosophila melanogaster</i> - Genome version Release ${WEB_PROPERTIES['genomeVersion.fly']} from <a href="http://www.flybase.org" target="_new">
                <html:img src="images/FlyBase_logo_mini.png" title="Click here to view FlyBase's website" />FlyBase</a>.
    </ul>

            <ul><li><i>Caenorhabditis elegans</i> - Genome version Release ${WEB_PROPERTIES['genomeVersion.worm']} from <a href="http://www.wormbase.org" target="_new">WormBase</a>
            </li></ul>
        </div>

<%--
        <h4>
          <a href="javascript:toggleDiv('hiddenDiv2');">
            <img id='hiddenDiv2Toggle' src="images/disclosed.gif" title="Click here to view more datasets"/>
            Minor data sets ...
          </a>
        </h4>

        <div id="hiddenDiv2" class="dataSetDescription">

          <p>
            More limited information is available
            for <i>C. elegans</i>, <i>S. cerevisiae</i> and others for
            comparison purposes.
          </p>

            <ul><li><i>Caenorhabditis elegans</i> - Genome information from <a href="http://www.wormbase.org" target="_new">WormBase</a>
            </li></ul>

        </div>

        <h4>
          <a href="javascript:toggleDiv('hiddenDiv3');">
            <img id='hiddenDiv3Toggle' src="images/disclosed.gif" title="Click here to view more datasets"/>
            EST data sets ...
          </a>
        </h4>

        <div id="hiddenDiv3" class="dataSetDescription">
          <dl>
            <ul><li><i>Anopheles gambiae</i> - Clustered EST data set version 8.0 from the 
              <a href="http://web.bioinformatics.ic.ac.uk/vectorbase/AnoEST.v8/index.php/" target="_new">Imperial College London Centre for Bioinformatics</a>.
            </dt>
          </li></ul>
        </div>
      </div>
--%>

   </td>
    <td width="40%" valign="top">
      <div class="body">
        <ul>

          <li>
            <im:querylink text="All <i>Drosophila melanogaster</i> gene identifiers and chromosomal positions " skipBuilder="true">
              <query name="" model="genomic" view="Gene.secondaryIdentifier Gene.name Gene.primaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.start Gene.chromosomeLocation.end">
                <node path="Gene" type="Gene">
                </node>
                <node path="Gene.organism" type="Organism">
                </node>
                <node path="Gene.organism.name" type="String">
                  <constraint op="=" value="Drosophila melanogaster" description="" identifier="" code="A">
                  </constraint>
                </node>
              </query>
            </im:querylink>
          </li>

          <li>
            <im:querylink text="All <i> Drosophila pseudoobscura</i> gene identifiers and chromosomal positions " skipBuilder="true">
              <query name="" model="genomic" view="Gene.secondaryIdentifier Gene.name Gene.primaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.start Gene.chromosomeLocation.end">
                <node path="Gene" type="Gene">
                </node>
                <node path="Gene.organism" type="Organism">
                </node>
                <node path="Gene.organism.name" type="String">
                  <constraint op="=" value="Drosophila pseudoobscura" description="" identifier="" code="A">
                  </constraint>
                </node>
              </query>
            </im:querylink>
          </li>
 
          <li>
          <im:querylink text="All <i> Drosophila mojavensis</i> gene identifiers and chromosomal positions " skipBuilder="true">
          <query name="" model="genomic" view="Gene.secondaryIdentifier Gene.name Gene.primaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.start Gene.chromosomeLocation.end">
            <node path="Gene" type="Gene">
            </node>
            <node path="Gene.organism" type="Organism">
            </node>
            <node path="Gene.organism.name" type="String">
              <constraint op="=" value="Drosophila mojavensis" description="" identifier="" code="A">
              </constraint>
            </node>
          </query>
        </im:querylink>
      </li>

          <li>
          <im:querylink text="All <i>Caenorhabditis elegans</i> gene identifiers and chromosomal positions " skipBuilder="true">
            <query name="" model="genomic" view="Gene.secondaryIdentifier Gene.name Gene.primaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.start Gene.chromosomeLocation.end">
              <node path="Gene" type="Gene">
              </node>
              <node path="Gene.organism" type="Organism">
              </node>
              <node path="Gene.organism.name" type="String">
                <constraint op="=" value="Caenorhabditis elegans" description="" identifier="" code="A">
                </constraint>
              </node>
            </query>
          </im:querylink>
        </li>

          
          
    </ul>
      </div>
    </td>
  </tr>

</table>
