#!/bin/sh

. /home/fh293/svn/dev/bio/scripts/flymine/init/bash/common.bashrc

LOGFILE="/home/fh293/logs/build-api-doc-`date +%Y-%m-%d`.log"

(cd ~/svn/dev
svn up

cd ~/svn/dev/bio/test-all/dbmodel
ant clean-all
ant build-db

cd ~/svn/dev/imbuild/javadoc
ant clean
ant
chmod -R a+rX build/javadoc/
if test "`find build/javadoc | wc -l`" -gt "1000" ; then
    rsync -avc --delete build/javadoc/ flymine@web0:/var/www/html/api/
else
    echo "Error with API documentation - see log file $LOGFILE for details" | mail -s "API Documentation failed" fh293@cam.ac.uk
fi
) >>$LOGFILE 2>&1
