#!/bin/sh -

files=`find . -name '*.java' -print`

wc $files > /tmp/java_count_tmp

(for i in $files
do
  perl -ne 'if (!m!^\s*//|^\s*/\*|^\s*\*|^\s*$!) {print}' $i | wc -l
done ) > /tmp/java_count_tmp_2

total=`perl -ne '$t += $_; END {printf ("%7d", $t)}' /tmp/java_count_tmp_2`
echo "$total" >> /tmp/java_count_tmp_2

paste /tmp/java_count_tmp_2 /tmp/java_count_tmp
