#!/bin/sh

# This will try and synchronise files on the local computer with files
# on a master. This is in order to try and keep all configuration files
# in sync with each other.

usage="Usage: $0 <remote repository>"

if [ $# -ne 1 ]
then
    echo $usage
    exit 1
fi

origdir=`pwd`

cd /software

command="rsync -e ssh -avz $1:/software/* ."
#echo $command
eval $command

cd $origdir
