#!/bin/sh

# Container for cronjob

PATH=/usr/local/bin:/software/arch/postgresql/bin:$PATH
export PATH

dumps_dir=/micklem/dumps/userprofile/flymine

$HOME/svn/trunk/bio/scripts/userprofile_backup $dumps_dir/incoming/userprofile_backup prod2 > $HOME/.userprofile_backup.output.new 2>&1

if cmp -s $HOME/.userprofile_backup.output $HOME/.userprofile_backup.output.new
then
    mv $HOME/.userprofile_backup.output.new $HOME/.userprofile_backup.output
else
    mv $HOME/.userprofile_backup.output.new $HOME/.userprofile_backup.output
    echo userprofile backup
    cat $HOME/.userprofile_backup.output
fi 

echo "-------------- Starting backup at `date`" >>$dumps_dir/log

cat $HOME/.userprofile_backup.output >>$dumps_dir/log

latest_version=`cat $HOME/.userprofile_latest_version`

if test -e "$dumps_dir/incoming/userprofile_backup.$latest_version" ; then
    DUMP_SIZE=`stat -c "%s" $dumps_dir/incoming/userprofile_backup.$latest_version`
    if test $DUMP_SIZE -lt "1000000" ; then
        echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version probably too small - backups may be broken" >>$dumps_dir/log
        echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version probably too small - backups may be broken" >&2
        exit 1
    fi
else
    echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version not created - backups may be broken" >>$dumps_dir/log
    echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version not created - backups may be broken" >&2
    exit 1
fi

if test -e "$dumps_dir/incoming/userprofile_backup.$latest_version.bags" ; then
    DUMP_SIZE=`stat -c "%s" $dumps_dir/incoming/userprofile_backup.$latest_version.bags`
    if test $DUMP_SIZE -lt "50000000" ; then
        echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version.bags probably too small - backups may be broken" >>$dumps_dir/log
        echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version.bags probably too small - backups may be broken" >&2
        exit 1
    fi
else
    echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version.bags not created - backups may be broken" >>$dumps_dir/log
    echo "Dump file $dumps_dir/incoming/userprofile_backup.$latest_version.bags not created - backups may be broken" >&2
    exit 1
fi

latest_version_major=`cat $HOME/.userprofile_latest_version | sed -e "s/^\([0-9]*\)\..*$/\1/"`

if ! test -e "$dumps_dir/r$latest_version_major" ; then
    mkdir $dumps_dir/r$latest_version_major
fi

mv $dumps_dir/incoming/userprofile_backup.$latest_version $dumps_dir/r$latest_version_major/userprofile_backup.$latest_version
mv $dumps_dir/incoming/userprofile_backup.$latest_version.bags $dumps_dir/r$latest_version_major/userprofile_backup.$latest_version.bags

( cd $dumps_dir/r$latest_version_major
 ci -mbackup -t-backup -l userprofile_backup.$latest_version
 ci -mbackup -t-backup -l userprofile_backup.$latest_version.bags
) >>$dumps_dir/log 2>&1

(cd $dumps_dir
 rm -f current_release_dump current_release_dump.bags
 ln -s r$latest_version_major/userprofile_backup.$latest_version current_release_dump
 ln -s r$latest_version_major/userprofile_backup.$latest_version.bags current_release_dump.bags
)

echo backup complete >> $dumps_dir/log

