#!/bin/sh

chgrp_chmod ()
{
    chgrp -R flymine $1
    chmod -R g+wX $1
}

chgrp_chmod "/export/shared_dmp_rel/*"
chgrp_chmod /export/shared_data

# for /downloads
chmod -R o+rX /export/releases/PUBLIC/*
