#!/bin/bash
if [ ! -f .mvnclasspath ]; then
    mvn dependency:build-classpath
fi
set CLASSPATH=target/classes:`cat .mvnclasspath`
java -ea -Xmx256M -classpath $CLASSPATH org.intermine.install.IntermineInstaller $*

