#!/usr/bin/perl

# process the output of performance_test for two releases and output templates
# that produce significantly different results - more than 10% more or fewer
# rows

if (@ARGV != 2) {
  die "$0: needs arguments - the names of the two log files to compare\n";
}

open my $f1, '<', $ARGV[0];
my %f1_results = read_results($f1);
close $f1;

open my $f2, '<', $ARGV[1];
my %f2_results = read_results($f2);
close $f2;

sub read_results
{
  my %res = ();

  my $file = shift;

  while (defined (my $line = <$file>)) {
    if ($line =~ /template (.*) returned (\d+) rows/) {
      $res{$1} = $2;
    }
  }

  return %res;
}

while ((my $tempname, my $count) = each %f1_results) {
  if (!exists $f2_results{$tempname}) {
    print "$tempname not in $ARGV[1]\n";
  }
}

print '-' x 70, "\n";

while ((my $tempname, my $count) = each %f2_results) {
  if (!exists $f1_results{$tempname}) {
    print "$tempname not in $ARGV[0]\n";
  }
}

print '-' x 70, "\n";

while ((my $f1_tempname, my $f1_count) = each %f1_results) {
  if (exists $f2_results{$f1_tempname}) {
    my $f2_count = $f2_results{$f1_tempname};

    my $diff = $f2_count;
    if ($f1_count > 0) {
        $diff = 1.0 * abs($f1_count - $f2_count) / $f1_count;
    }
    if (($f1_count != $f2_count && $diff > 0.1) || $f2_count == 0 || $f1_count == 0) {
      printf ("%-45s %s: %6.0f, %s: %6.0f, diff: %d%%\n",
              $f1_tempname, $ARGV[0], $f1_count, $ARGV[1], $f2_count, $diff * 100);
    }
  }
}

print '-' x 70, "\n";

while ((my $f1_tempname, my $f1_count) = each %f1_results) {
  if (exists $f2_results{$f1_tempname}) {
    my $f2_count = $f2_results{$f1_tempname};

    my $diff = $f2_count;
    if ($f1_count > 0) {
        $diff = 1.0 * abs($f1_count - $f2_count) / $f1_count;
    }
    if ($diff <= 0.1 && ($f1_count < 100 || $f2_count < 100)) {
      printf ("%-45s %s: %6.0f, %s: %6.0f, diff: %d%%\n",
              $f1_tempname, $ARGV[0], $f1_count, $ARGV[1], $f2_count, $diff * 100);
    }
  }
}
