#!/usr/bin/perl
# script to download ncbi gene number and pubmed ID files

use strict;

use lib "../../intermine/perl/lib/InterMine/";
use DataDownloader;

print "\nReady to download NCBI gene and pubmed Id...\n";

#for connecting to the ftp server
my $ncbi_server = "ftp.ncbi.nlm.nih.gov";
my $ncbi_dir = "gene/DATA";
my $username = "anonymous";
my $password = "philip\@flymine.org";

#files to download
my $gene_info_file = "gene_info.gz";
my $pubmed_info_file = "gene2pubmed.gz";

#connect to the server
my $connection = &ftp_connect($ncbi_server,$ncbi_dir,$username,$password);

#use the date stamp to create a version id for the output directory
my $gene_date_string = &date_string($connection,$gene_info_file);
my $pubmed_date_string = &date_string($connection, $pubmed_info_file);

#destination directories
my $ncbi_main_dir = "/shared/data/pubmed";
my $ncbi_gene_dir = "$ncbi_main_dir/gene_info/$gene_date_string";
my $pubmed_id_dir = "$ncbi_main_dir/gene2pubmed/$pubmed_date_string";

#make sure that the necessary directories exist
&checkdir($ncbi_main_dir);
&checkdir("$ncbi_main_dir/gene_info");
&checkdir("$ncbi_main_dir/gene2pubmed");
&checkdir("$ncbi_main_dir/current");

#if a file is downloaded, update the links in the "current" directory
if(&download($connection,$pubmed_id_dir,$pubmed_info_file) == 1){
	my $pub_link = "/shared/data/pubmed/current/gene2pubmed";
	my $pub_current_dir = "/shared/data/pubmed/gene2pubmed/$pubmed_date_string";
	&make_link($pub_current_dir,$pub_link);
}
if(&download($connection,$ncbi_gene_dir,$gene_info_file) == 1){
	my $gene_link = "/shared/data/pubmed/current/gene_info";
	my $gene_current_dir = "/shared/data/pubmed/gene_info/$gene_date_string";
	&make_link($gene_current_dir,$gene_link);
  
}

$connection->quit;

