#!/usr/bin/perl

#Script to get the affy locations for all genes and transcripts.
#Bert Overduin 8 August 2008.

use strict;
use Bio::EnsEMBL::Registry;

my $registry = 'Bio::EnsEMBL::Registry';

$registry->load_registry_from_db (
        -host => 'ensembldb.ensembl.org',
        -user => 'anonymous'
        );

open(OUTFILE, ">AFFY_Drosophila_2.txt");

my $sa = $registry->get_adaptor('fly','core','Slice');
my $ofa = $registry->get_adaptor('fly','core','OligoFeature');

my @slices = @{$sa->fetch_all('toplevel')};

foreach my $slice(@slices){
        my @genes = @{$slice->get_all_Genes};
        foreach my $gene(@genes){
                my @transcripts = @{$gene->get_all_Transcripts};
                foreach my $transcript(@transcripts){
                        my @xrefs = @{$transcript->get_all_DBEntries};
                        foreach my $xref(@xrefs){
                                if($xref->dbname eq 'AFFY_Drosophila_2'){
                                        my @probe_features =
@{$ofa->fetch_all_by_probeset($xref->display_id)};
                                                foreach my
$probe_feature(@probe_features){
                                                        print(OUTFILE
$gene->stable_id, "\t", $transcript->stable_id, "\t", $xref->display_id,
"\t",
$probe_feature->seq_region_name, "\t", $probe_feature->seq_region_start,
"\t", $probe_feature->seq_region_end, "\n");
                                                }
                                }
                        }
                }
        }
}