#!/usr/bin/perl
# script to download ncbi gene number and pubmed ID files

use strict;

use lib "../../intermine/perl/lib/InterMine/";
use DataDownloader;

print "\nReady to download NCBI gene and pubmed Id...\n";

#for connecting to the ftp server
my $ncbi_server = "ftp.ncbi.nlm.nih.gov";
my $ncbi_dir = "gene/DATA";
my $username = "anonymous";
my $password = "philip\@flymine.org";

#files to download
my $gene_info_file = "gene_info.gz";
my $pubmed_info_file = "gene2pubmed.gz";

#connect to the server and change to source directory
my $connection = &ftp_connect($ncbi_server,$username,$password);
	
$connection->cwd($ncbi_dir)
	or die "Cannot change working directory ", $connection->message;

#use the date stamp to create a version id for the output directory
my $date_string = &date_string_file($connection,$pubmed_info_file);

#destination directories
my $ncbi_main_dir = "/shared/data/pubmed";
my $download_dir = "$ncbi_main_dir/$date_string";

#make sure that the necessary directories exist
&checkdir_exists($ncbi_main_dir);

if(&checkdir_exists($download_dir)==1){
	&download($connection,$download_dir,$gene_info_file);
	&download($connection,$download_dir,$pubmed_info_file);
}else{
	warn " current version up to date - skipping download\n";
}

&unzip_dir($download_dir);

my $current_link = "/shared/data/pubmed/current_source";
&make_link($download_dir,$current_link);

$connection->quit;

