#!/usr/bin/perl

#downloads genes2molecular_names.txt from http://www.sanger.ac.uk/Projects/C_elegans/LOCI
#and compares it to the version pointed to by the current link in /shared/data/wormbase
#as a current version id for genes2molecular_names.txt is not avaiable prior to download.

use strict;
use warnings;

BEGIN {
  # find the lib directory by looking at the path to this script
  push (@INC, ($0 =~ m:(.*)/.*:)[0] . '/../../intermine/perl/lib/');
}
use InterMine::DataDownloader;

#data source
my $wb_id_server = "http://www.sanger.ac.uk/Projects/C_elegans/LOCI";
my $wb_id_data_file = "genes2molecular_names.txt";
my $file_to_get = "$wb_id_server/$wb_id_data_file";

#data destination
my $wb_main_dir = "/shared/data/wormbase";
my $download_dir = "$wb_main_dir/temp";
my $temp_file = "$download_dir/temp.txt";
my $tab_delim_file = "$download_dir/$wb_id_data_file";

#create directories and download the file
&checkdir_exists($wb_main_dir);
&checkdir_exists($download_dir);
&http_download($file_to_get,$temp_file);

#convert it from a space delimited to tab delimited file
open(F,"<$temp_file") or die "cannot open $temp_file: $!";
open(FH,">$tab_delim_file") or die "cannot open $tab_delim_file: $!";
while(<F>){
	#substitute a space with a tab for each line
	s/ /\t/g;
    print FH; 
}
close(F) or die "$!";
close(FH) or die "$!";
unlink $temp_file;

my $current_link = "/shared/data/wormbase/current";
my $old_file = "$current_link/genes2molecular_names.txt";
my ($version_buffer,$log_buffer);

#compare the files, create version directory if it is a new version or
#the current data link is missing
if(&compare_files($old_file,$tab_delim_file)==1){
	print "Keeping downloaded files.\n";
	&update_files($wb_main_dir,$wb_id_data_file,$tab_delim_file,$current_link);
}else{	
	print "Downloaded files deleted.\n";
	unlink $tab_delim_file;
	$log_buffer = "WormBase Identifiers\nCurrent data ok\n\n";
}

&write_log($log_buffer);
	
#create data directory, move files, make link	
sub update_files(){
	my ($dir,$new_name,$oldfile,$link) = @_;
	my $date = &convert_date();
	my $new_dir = "$dir/$date";
	my $newfile = "$new_dir/$new_name";
	&checkdir_exists($new_dir);
	rename($oldfile, $newfile) or die "Cannot rename $oldfile: $!";
	&make_link($date,$link);
	
	$log_buffer = "WormBase Identifiers\nNew data available in $new_dir containing file $new_name\n\n"; 
	$version_buffer = "WormBase Identifiers\n$date\nThe database of the genetics, genomics and biology of Caenorhabditis elegans.\nhttp://www.wormbase.org/\n";
	&write_version($dir,$version_buffer);
	system "chmod -R a+r,g+w $new_dir";
}	
