#!/usr/bin/python                                                                                                                                                                                                                                                         

import urllib
import subprocess
import sys

if len(sys.argv) != 3:
    script = sys.argv[0].rsplit('/')[-1]
    print "Usage: " + script + " homo_sapiens|mus_musculus version\n\te.g. " + script + " homo_sapiens 60"
    exit(1);

organism = sys.argv[1]
version = sys.argv[2]

max_chr = 23
base = ''
if organism == 'homo_sapiens':
    base = 'Homo_sapiens.GRCh37.'
elif organism == 'mus_musculus':
    base = 'Mus_musculus.NCBIM37.'
    max_chr = 20
else:
    print "Didn't recognise organism '" + organism + "'."


chrs = ['X', 'Y', 'MT'] + range(1, max_chr)
print 'Looking for chromosomes: ', chrs    

ensembl_ftp = 'ftp://ftp.ensembl.org/'
fasta_dir = 'pub/current_fasta/' + organism + '/dna/'

for chr in chrs:
    filename = base + version + '.dna.chromosome.' + str(chr) + '.fa.gz'
    path = ensembl_ftp + fasta_dir + filename
    print 'Fetching ' + path
    urllib.urlretrieve(path, filename)
    command = 'gunzip ' + filename
    print 'Unzipping ' + filename
    subprocess.call(['gunzip', filename])


