#!/usr/bin/perl
# script to download WormBase RNAi and phenotype ontology files
#produces two files phenotype_association.WSNNN.wb and 
#phenotype_ontology.WSNNN.obo

use strict;
use Archive::Extract;
use Archive::Tar;

BEGIN {
  # find the lib directory by looking at the path to this script
  push (@INC, ($0 =~ m:(.*)/.*:)[0] . '/../../intermine/perl/lib/');
}
use InterMine::DataDownloader;

#Define ARGVs
my ($logdir,$logname,$home);
if(@ARGV!=3){
	die "Wrong number of ARGVs!\nget_all.sh should supply the log directory, temporary log name, and /shared/data/.\n";
}else{
	$logdir = $ARGV[0];
	$logname= $ARGV[1];
	$home = $ARGV[2];
}

#for connecting to the ftp server
my $wormbase_ftp = "caltech.wormbase.org";
my $ftp_dir = "pub/igor/tmp";
my $username = "anonymous";
my $password = "-anonymous\@";

#connect to the server and change to source directory
my $connection = &ftp_connect($wormbase_ftp,$username,$password);
$connection->cwd($ftp_dir)
		or die "Cannot change working directory ", $connection->message;	

#identify the latest ontology file to download using the date stamp
my $date_string;
my $ftp_file;
my $version;

#get the list of files
my @files = $connection->ls();
foreach my $file (@files) {
	#identify the ontology files
	if($file =~ /^ontology\.(WS\d+)\.tar\.gz/g){
		my $date = &date_string_file($connection,$file);
		#if this date is newer than the previous date, we want this file and it's version number
		if($date gt $date_string){
			$date_string = $date;
			$ftp_file = $file;
			$version = $1;
		}
	}
}

# check download directory exists
my $main_dir = "$home/rnai/wormbase";
my $download_dir = "$main_dir/$date_string";
&checkdir_exists($main_dir);

my ($version_buffer,$log_buffer);
#if download dir doesn't exist, create it and download data
if(&checkdir_exists($download_dir)==1){
	&ftp_download($connection,$download_dir,$ftp_file);
	
	#extract the files from the tar archive
	my $ae = Archive::Extract->new(archive => "$download_dir/$ftp_file");
	$ae->extract( to => $download_dir );
	
	#remove unnecessary files included in the archive
	system "rm $download_dir/gene* $download_dir/anatomy* $download_dir/*.gz";
	
	my $current_link = "$home/rnai/wormbase/current";
	&make_link($date_string,$current_link);
	
	$version_buffer = "C. elegans RNAi phenotypes\n$version $date_string\n"
						."RNAi phenotypes for C. elegans from WormBase\n"
						."http://www.wormbase.org\n";
	$log_buffer = "Wormbase RNAi\nNew data (version $version) is available in $download_dir\n\n";
	&write_version($main_dir,$version_buffer);
	system "chmod -R a+r,g+w $download_dir";
	
}else{ 
	warn " current version up to date - skipping download\n";
	$log_buffer = "Wormbase RNAi\nCurrent data ok\n\n";
}
&write_log($log_buffer,$logdir,$logname);







