#!/usr/bin/perl

# script to download PSI data from IntAct - currently has a list of accepted
# organisms hard-coded, should be passed in as a list.
# Will downoad to ./psi/intact/release_date
use strict;
use warnings;

use lib "../../intermine/perl/lib/InterMine/";
use DataDownloader;

my $ebi_server = "ftp.ebi.ac.uk";
my $intact_dir = "pub/databases/intact/current/";
my $species_dir = "psi1/species";
my $username = "anonymous";
my $password = "-anonymous\@";

# list of organisms to get - this is the five letter abbreviation used as the
# start of intact filenames.  Add more to this list to get more organisms
#my @organisms = ("drome", "caeel", "yeast");
my @organisms = ("human", "mouse", "rat", "bovin", "sheep");

#### Access EBI ftp server
my $connection = &ftp_connect($ebi_server,$username,$password);
    
$connection->cwd($intact_dir)
	or die "Cannot change working directory ", $connection->message;

#use the date stamp of a file in the $intact_dir to create a version id 
#for the output directory
my $check_file = "all.zip";
my $date_string = &date_string_file($connection,$check_file);

# check psi and intact directory exists
my $psi_dir = "/shared/data/psi";
my $intact_main_dir = "$psi_dir/intact";
my $download_dir = "$intact_main_dir/$date_string";

&checkdir_exists($psi_dir);
&checkdir_exists($intact_main_dir);

#if download dir doesn't exist, create it and download data
if(&checkdir_exists($download_dir)==1){
	$connection->cwd($species_dir)
 	   or die "Cannot change working directory to $species_dir";

	my @psi_files = $connection->ls();

	for my $psi_file (@psi_files) {
	    my $start = substr($psi_file, 0, index($psi_file, "_"));
	    if (grep {$start eq $_} @organisms) {
	        &download($connection,$download_dir,$psi_file);
	    }
	}
}else{ 
	warn " current version up to date - skipping download\n";
}

my $current_link = "/shared/data/psi/intact/current";
&make_link($date_string,$current_link);

$connection->quit;
