#!/usr/bin/perl

# script to download PSI data from IntAct to ./psi/intact/release_date
use strict;
use warnings;

BEGIN {
  # find the lib directory by looking at the path to this script
  push (@INC, ($0 =~ m:(.*)/.*:)[0] . '/../../intermine/perl/lib/');
}
use InterMine::DataDownloader;

my $ebi_server = "ftp.ebi.ac.uk";
my $intact_dir = "pub/databases/intact/current/";
my $species_dir = "psi1/species";
my $username = "anonymous";
my $password = "-anonymous\@";

# get the list of organisms from the config file - this is the five letter
# abbreviation used as the start of intact filenames. 
my $file = "/shared/data/taxonID.config";
my %organisms = &config_species($file,"intact");

#### Access EBI ftp server
my $connection = &ftp_connect($ebi_server,$username,$password);

$connection->cwd($intact_dir)
	or die "Cannot change working directory ", $connection->message;

#use the date stamp of a file in the $intact_dir to create a version id 
#for the output directory
my $check_file = "all.zip";
my $date_string = &date_string_file($connection,$check_file);

# check psi and intact directory exists
my $psi_dir = "/shared/data/psi";
my $intact_main_dir = "$psi_dir/intact";
my $download_dir = "$intact_main_dir/$date_string";

&checkdir_exists($psi_dir);
&checkdir_exists($intact_main_dir);

#if download dir doesn't exist, create it and download data
if(&checkdir_exists($download_dir)==1){
	$connection->cwd($species_dir)
 	   or die "Cannot change working directory to $species_dir";

	my @psi_files = $connection->ls();

	for my $psi_file (@psi_files) {
	    my $start = substr($psi_file, 0, index($psi_file, "_"));
		if (grep {$start eq $_} keys %organisms) {
	        &ftp_download($connection,$download_dir,$psi_file);
	    }
	}
	
	my $current_link = "/shared/data/psi/intact/current";
	&make_link($date_string,$current_link);
}else{ 
	warn " current version up to date - skipping download\n";
}

$connection->quit;

#================================================================================
#download psi-mi.obo from http://www.berkeleybop.org/ontologies/obo-all/psi-mi/
#to /shared/data/psi/ontology/
#seems to be updated every week

#NOTE: eventually the data might be moved to http://www.bioontology.org/ncbo/faces/index.xhtml

my $psi_mi_server = "http://www.berkeleybop.org/ontologies/obo-all/psi-mi";
my $psi_mi_data_file = "psi-mi.obo";

my $psi_mi_download_dir = "$psi_dir/ontology";
my $file_to_get = "$psi_mi_server/$psi_mi_data_file";
my $data_file = "$psi_mi_download_dir/$psi_mi_data_file";

&checkdir_exists($psi_mi_download_dir);
&http_download($file_to_get,$data_file);
