#!/usr/bin/perl

# script to download interpro.xml.gz from ftp.ebi.ac.uk/pub/databases/interpro/

use strict;
use warnings;

BEGIN {
  # find the lib directory by looking at the path to this script
  push (@INC, ($0 =~ m:(.*)/.*:)[0] . '/../../intermine/perl/lib/');
}
use InterMine::DataDownloader;

#Define ARGVs
my ($logdir,$logname,$home);
if(@ARGV!=3){
	die "Wrong number of ARGVs!\nget_all.sh should supply the log directory, temporary log name, and /shared/data/.\n";
}else{
	$logdir = $ARGV[0];
	$logname= $ARGV[1];
	$home = $ARGV[2];
}

# EBI ftp server information
my $ebi_server = "ftp.ebi.ac.uk";
my $interpro_dir = "pub/databases/interpro/";
my $username = "anonymous";
my $password = "-anonymous\@";

#### Access EBI ftp server
my $connection = &ftp_connect($ebi_server,$username,$password);

$connection->cwd($interpro_dir)
	or die "Cannot change working directory ", $connection->message;
	
#use the date stamp of interpro.xml.gz to create a version id for the output directory
my $interpro_file = "interpro.xml";
my $date_string = &date_string_file($connection,"$interpro_file.gz");

# check interpro directory exists
my $main_dir = "$home/interpro";
my $download_dir = "$main_dir/$date_string";
&checkdir_exists($main_dir);

my ($version,$version_buffer,$log_buffer);
#if download dir doesn't exist, create it and download data
if(&checkdir_exists($download_dir)==1){
	&ftp_download($connection,$download_dir,"$interpro_file.gz");
	&unzip_dir($download_dir);	
	my $current_link = "$home/interpro/current";
	&make_link($date_string,$current_link);
	
	#get the interpro version from the downloaded file
	open(F,"<$download_dir/$interpro_file") or die "$! can't open $interpro_file";
	while(my $newline = <F>){
		if($newline && $newline =~ /dbname="INTERPRO" version="(\S+)"/gi){
			$version = $1;
		}
	}
	$version_buffer = "InterPro protein family and domain data\n$version $date_string\n"
						."Protein Family and Domain data for D. melanogaster, A. gambiae and C. elegans from Interpro\n"
						."http://www.ebi.ac.uk/interpro\n";
	$log_buffer = "Interpro\nNew version $version is available in $download_dir containing file $interpro_file\n\n";
	&write_version($main_dir,$version_buffer);
	system "chmod -R a+r,g+w $download_dir";
}else{ 
	warn " current version up to date - skipping download\n";
	$log_buffer = "Interpro\nCurrent data ok\n\n";
}
&write_log($log_buffer,$logdir,$logname);
