#!/bin/bash

if [ $# -ne 4 ]
then
    echo "expecting: $0 mine model namespace filename"
    echo "eg. flymine sofa org.intermine.bio so_terms ";
    exit
fi

whichmine=$1
export newModelName=$2
namespace=$3
filename=$4

export INTERMINE=~/svn/dev/intermine
export MINE=~/svn/dev/$whichmine
export BIO=~/svn/dev/bio

CP=$CLASSPATH

CP=$CP:$INTERMINE/objectstore/main/dist/intermine-objectstore.jar
for i in $INTERMINE/objectstore/main/lib/*.jar ; do
    CP=$CP:$i
done
CP=$CP:$BIO/core/main/dist/genomic-tasks.jar
for i in $BIO/core/main/lib/*.jar ; do
    CP=$CP:$i
done

if test -z "$LD_LIBRARY_PATH" ; then
    export LD_LIBRARY_PATH=/usr/lib:/lib:/usr/lib/jni
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/lib:/usr/lib/jni
fi

#echo "Using classpath: $CP"
#echo "Using LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

oboFileName=$BIO/sources/so/$newModelName.obo 
modelFileName=~/svn/dev/$whichmine/dbmodel/build/model/${newModelName}_model.xml

java -cp $CP -Xmx1000M org.intermine.bio.ontology.OboToModel $newModelName $oboFileName $modelFileName $namespace $filename

