#!/bin/bash

# The following environment variables need to be set
# INTERMINE: location of local InterMine installation

export whichmine=$*

export INTERMINE=~/svn/dev/intermine
export MINE=~/svn/dev/$whichmine
export BIO=~/svn/dev/bio

CP=$CLASSPATH

CP=$CP:$INTERMINE/objectstore/main/dist/intermine-objectstore.jar
for i in $INTERMINE/objectstore/main/lib/*.jar ; do
    CP=$CP:$i
done
for i in $INTERMINE/api/main/lib/*.jar ; do
    CP=$CP:$i
done
CP=$CP:$INTERMINE/api/main/dist/intermine-api.jar
#CP=$CP:$INTERMINE/api/main/lib/lucene-core-2.3.2.jar
CP=$CP:$INTERMINE/web/main/dist/intermine-web.jar
CP=$CP:$INTERMINE/webtasks/main/dist/intermine-web.jar
CP=$CP:$INTERMINE/webtasks/main/dist/intermine-webapp-tasks.jar
CP=$CP:$INTERMINE/pathquery/main/dist/intermine-pathquery.jar
CP=$CP:$INTERMINE/api/model/userprofile/dist/userprofile.jar
for i in $INTERMINE/web/main/lib/*.jar ; do
    CP=$CP:$i
done
CP=$CP:$BIO/webapp/resources
CP=$CP:~
CP=$CP:$MINE/webapp/build/main
CP=$CP:$MINE/dbmodel/build/model
CP=$CP:$MINE/dbmodel/build/classes
CP=$CP:$MINE/dbmodel/resources

if test -z "$LD_LIBRARY_PATH" ; then
    export LD_LIBRARY_PATH=/usr/lib:/lib:/usr/lib/jni
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/lib:/usr/lib/jni
fi

echo "Using classpath: $CP"
echo "Using LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

java -cp $CP -Xmx1000M org.intermine.web.commandline.PerformanceTester 20 

