#!/usr/bin/perl

use warnings;
use strict;

use IO::All;
use URI::Escape;

my $query = io('-')->slurp;

$query = uri_escape($query);

io->http("http://www.flymine.org/query/service/query/results?size=100000&query=$query") > io('-');
