#!/bin/bash

LOG=/var/log/number1_sync_mirror.log

exec > $LOG

export RSYNC_RSH="ssh -i /AUTOMATION/id_dsa_backup_gen_rsync"

DEST="backup-flymine.gen.private.cam.ac.uk:/BACKUP/data/number1/"

rsync -av  --delete /export/home $DEST
rsync -av  --delete /export/misc $DEST
rsync -av  --delete /export/production $DEST
rsync -av  --delete /export/share $DEST
rsync -av  --delete /export/archives $DEST
