#!/bin/bash
#
# default usage: bup_userprofile
#
# note used by crontab 
#
# TODO: add cleaning procedure (how much/what do we want to keep?)
#
# sc

ARKDIR=/micklem/releases/modmine/bups
PROPDIR=/home/modmine/.intermine
DBHOST=modfast
DBUSER=modmine
INTERACT=y
DOIT=y

TIMESTAMP=`date "+%y%m%d-%H%M"`

RETURNDIR=$PWD

pwd

if [ -z "$1" ]
then
echo
echo -n "Reading latest modMine release number: "
cd $PROPDIR
REL=`ls -1 modmine.properties.r* | sed 's/modmine.properties.r//g' | sort -n | tail -1`
cd $RETURNDIR
else
REL="$1"
fi
echo $REL

if [ ! -s "$ARKDIR/$REL" ]
then
echo
echo "Creating directory $ARKDIR/$REL..."
mkdir $ARKDIR/$REL
fi

cd $ARKDIR
echo "compressing old files.."
gzip *.sql
mv *.gz $REL

echo "pg_dump -c -h modprod0 -U modmine -t osbag_int modmine-r$REL > $ARKDIR/osbag_int-$TIMESTAMP.sql"
pg_dump -c -h modprod0 -U modmine -t osbag_int modmine-r$REL > $ARKDIR/osbag_int-$TIMESTAMP.sql

echo "pg_dump -c -i -h modprod0 -U modmine -f $ARKDIR/modmine-r$REL-userprofile-$TIMESTAMP.sql modmine-r$REL-userprofile"
pg_dump -c -i -h modprod0 -U modmine -f $ARKDIR/modmine-prod-userprofile-$TIMESTAMP.sql modmine-prod-userprofile
