#!/bin/bash

LOG=/var/log/fileserver_sync_mirror.log

exec > $LOG

export RSYNC_RSH="ssh -i /AUTOMATION/id_dsa_backup_gen_rsync"

DEST="backup-flymine.gen.private.cam.ac.uk:/BACKUP/data/fileserver1/"

rsync -av  --delete /export/software $DEST
rsync -av  --delete /export/shared_data $DEST
rsync -av  --delete /export/shared_dmp_rel $DEST
