// This file is automatically generated. Any changes may be lost.
// The following declarations describes all resources that might be loaded dynamically.

// Brush Aliases
Syntax.alias("apache", []);
Syntax.alias("applescript", []);
Syntax.alias("asm", []);
Syntax.alias("bash-script", []);
Syntax.alias("bash", []);
Syntax.alias("basic", ['vb']);
Syntax.alias("clang", ["cpp", "c++", "c", "objective-c"]);
Syntax.alias("csharp", ["c#"]);
Syntax.alias("css", []);
Syntax.alias("diff", ["patch"]);
Syntax.alias("haskell", []);
Syntax.alias("html", ["xml"]);
Syntax.alias("java", []);
Syntax.alias("javascript", ["js", "actionscript"]);
Syntax.alias("lisp", ['scheme', 'clojure']);
Syntax.alias("lua", []);
Syntax.alias("ooc", []);
Syntax.alias("pascal", ["delphi"]);
Syntax.alias("perl5", []);
Syntax.alias("php-script", []);
Syntax.alias("php", []);
Syntax.alias("plain", ["text"]);
Syntax.alias("python", []);
Syntax.alias("ruby", []);
Syntax.alias("smalltalk", []);
Syntax.alias("sql", []);
Syntax.alias("yaml", []);

// CSS Extensions
Syntax.styles["jquery.syntax.brush.apache"] = "jquery.syntax.brush.apache.css";
Syntax.styles["jquery.syntax.brush.applescript"] = "jquery.syntax.brush.applescript.css";
Syntax.styles["jquery.syntax.brush.asm"] = "jquery.syntax.brush.asm.css";
Syntax.styles["jquery.syntax.brush.bash-script"] = "jquery.syntax.brush.bash-script.css";
Syntax.styles["jquery.syntax.brush.bash"] = "jquery.syntax.brush.bash.css";
Syntax.styles["jquery.syntax.brush.clang"] = "jquery.syntax.brush.clang.css";
Syntax.styles["jquery.syntax.brush.css"] = "jquery.syntax.brush.css.css";
Syntax.styles["jquery.syntax.brush.diff"] = "jquery.syntax.brush.diff.css";
Syntax.styles["jquery.syntax.brush.html"] = "jquery.syntax.brush.html.css";
Syntax.styles["jquery.syntax.brush.python"] = "jquery.syntax.brush.python.css";
Syntax.styles["jquery.syntax.core"] = "jquery.syntax.core.css";
Syntax.styles["jquery.syntax.layout.fixed"] = "jquery.syntax.layout.fixed.css";
Syntax.styles["jquery.syntax.layout.inline"] = "jquery.syntax.layout.inline.css";
Syntax.styles["jquery.syntax.layout.list"] = "jquery.syntax.layout.list.css";
Syntax.styles["jquery.syntax.layout.table"] = "jquery.syntax.layout.table.css";
