<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="im" %>

<table width="100%">
  <tr>
    <td valign="top">
      <div class="heading2">
        Current data
      </div>
    </td>
    <td valign="top">
      <div class="heading2">
        Bulk download
      </div>
    </td>
  </tr>
  <tr>
    <td valign="top">
      <div class="body" style="height:1%">


      <li>
      <dt>A set of 3-D structural domain predictions for <i>D. melanogaster</i> proteins generated by
      <a href="http://www-cryst.bioc.cam.ac.uk/~kenji/NEW/index.htm" target="_new">Kenji Mizuguchi</a>
      is available.<br/>     </dt>

      <dt>3-D structural predictions were calculated for regions of
      the <I>D. melanogaster</I> release 3.1 peptides to which an
      <a href="http://www.ebi.ac.uk/interpro" target="_new">interpro</a> domain assignment had been
      made (only <a href="http://www.sanger.ac.uk/Software/Pfam" target="_new">PFam</a> domains
      were taken).  Stuctural data for each of these fragments is
      available in UniMine. Currently the atomic coordinates for each
      structure together with a sequence-structure compatibility score
      (z-score) and a q-score are available. The <a href="http://www.jmol.org" target="_new">JMol structural viewer</a> has been
      integrated into UniMine and allows viewing and further analysis of each domain
      structure. In the future the sequence-structure alignments will also be
      loaded. 
    </dt>
    </li>
    <li>
    <dt>Experimentally determined protein structures for <I>D. melanogaster</I> from the <a href="http://www.rcsb.org/pdb/home/home.do" target="_new">RCSB Protein data Bank.</a>
    </dt>
    </li>
   </div> 	
  </td>


    <td width="40%" valign="top">
      <div class="body">
        <ul>


        <li>
            <im:querylink text="All 3-D protein structure data for <i>Homo sapiens</i> (PDB data) " skipBuilder="true">
<query name="" model="genomic" view="Protein.primaryIdentifier Protein.name Protein.structures.title Protein.structures.technique Protein.structures.resolution" sortOrder="Protein.primaryIdentifier asc">
  <node path="Protein" type="Protein">
  </node>
  <node path="Protein.organism" type="Organism">
  </node>
  <node path="Protein.organism.name" type="String">
    <constraint op="=" value="Homo sapiens" description="" identifier="" code="A">
    </constraint>
  </node>
</query>
            </im:querylink>
        </li>

        <li>
            <im:querylink text="All 3-D protein structure data for <i>D. melanogaster</i> (PDB data) " skipBuilder="true">
               <query name="" model="genomic" view="Protein.primaryIdentifier Protein.name Protein.structures.title Protein.structures.technique Protein.structures.resolution" sortOrder="Protein.primaryIdentifier asc">
  <node path="Protein" type="Protein">
  </node>
  <node path="Protein.organism" type="Organism">
  </node>
  <node path="Protein.organism.name" type="String">
    <constraint op="=" value="Drosophila melanogaster" description="" identifier="" code="A">
    </constraint>
  </node>
</query>           
            </im:querylink>
        </li>

        <li>
            <im:querylink text="All 3-D protein structure data for <i>Mus musculus</i> (PDB data) " skipBuilder="true">
            <query name="" model="genomic" view="Protein.primaryIdentifier Protein.name Protein.structures.title Protein.structures.technique Protein.structures.resolution" sortOrder="Protein.primaryIdentifier asc">
  <node path="Protein" type="Protein">
  </node>
  <node path="Protein.organism" type="Organism">
  </node>
  <node path="Protein.organism.name" type="String">
    <constraint op="=" value="Mus musculus" description="" identifier="" code="A">
    </constraint>
  </node>
</query>
            </im:querylink>
         </li>


          <li>
            <im:querylink text="All 3-D protein structure data for <i>Saccharomyces cerevisiae</i> (PDB data) " skipBuilder="true">
<query name="" model="genomic" view="Protein.primaryIdentifier Protein.name Protein.structures.title Protein.structures.technique Protein.structures.resolution" sortOrder="Protein.primaryIdentifier asc">
  <node path="Protein" type="Protein">
  </node>
  <node path="Protein.organism" type="Organism">
  </node>
  <node path="Protein.organism.name" type="String">
    <constraint op="=" value="Saccharomyces cerevisiae" description="" identifier="" code="A">
    </constraint>
  </node>
</query>
            </im:querylink>
         </li>


          <li>
            <im:querylink text="All 3-D protein structure data" skipBuilder="true">
  <query name="" model="genomic" view="Protein.organism.name Protein.primaryAccession Protein.name Protein.structures.identifier Protein.structures.evidence.title" sortOrder="Protein.organism.name Protein.primaryAccession Protein.name Protein.structures.identifier Protein.structures.evidence.title">
</query>
            </im:querylink>
          </li>

     </ul>
    </div>
    </td>
  </tr>
</table>
