#!/bin/csh
#module purge
#module load java-tig
#module load ant

setenv ANT_HOME /usr/share/ant/
java -agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y -classpath ${ANT_HOME}/lib/ant-launcher.jar -Dant.home=${ANT_HOME} -Dant.library.dir=${ANT_HOME}/lib org.apache.tools.ant.launch.Launcher -cp /global/u1/j/jcarlson/lib/jar/mysql-connector-java-5.1.6.jar -v -Dsource=inparanoid-homologs




