#!/bin/csh
#module purge
#module load java-tig
#module load ant

setenv ANT_HOME /usr/share/ant/

java -agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y -classpath ${ANT_HOME}/lib/ant-launcher.jar -Dant.home=${ANT_HOME} -Dant.library.dir=${ANT_HOME}/lib org.apache.tools.ant.launch.Launcher -cp "" -Dsource=tsv-synonyms

##java -agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y -classpath /usr/common/usg/utilities/ant/1.8.4/lib/ant-launcher.jar -Dant.home=/usr/common/usg/utilities/ant/1.8.4 -Dant.library.dir= /usr/common/usg/utilities/ant/1.8.4/lib org.apache.tools.ant.launch.Launcher -cp "" -Dsource=phytozome-chado-Z.mays


