---
# yamllint disable rule:line-length
name: Checkstyle
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - .github/workflows/checkstyle.yml
            - 'bio/**'
            - 'config/**'
            - 'docs/**'
            - 'intermine/**'
            - 'plugin/**'
            - 'testmine/**'

jobs:
    checkstyle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Set up JDK 8
              uses: actions/setup-java@v5
              with:
                  distribution: 'zulu'
                  java-version: '8'
            - name: Set up python 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
            - name: Check style
              run: |
                  set -euxo pipefail
                  ./config/ci/init.sh ${GITHUB_WORKSPACE} $(which python3) checkstyle none none
                  ./config/ci/run.sh ${GITHUB_WORKSPACE} $(which python3) checkstyle none none
