name: InterMine CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres:11
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      TESTMODEL_PATH: intermine-demo
    strategy:
      fail-fast: true
      matrix:
        testSuite: [intermine, bio]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Set up python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install PostgreSQL client
      run: |
        set -euo pipefail
        sudo apt-get update -y
        sudo apt-get install -y libpq-dev postgresql-client
    - name: Run unit tests
      run: |
        set -euo pipefail
        mkdir -p ${HOME}/.gradle
        cp config/ci/gradle.properties ${HOME}/.gradle
        ./config/ci/init.sh ${GITHUB_WORKSPACE} $(which python3) ${{ matrix.testSuite }} none http://localhost:8080/intermine-demo
        ./config/ci/run.sh ${GITHUB_WORKSPACE} $(which python3) ${{ matrix.testSuite }} none http://localhost:8080/intermine-demo

  ws-tests:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      TESTMODEL_PATH: intermine-demo
    strategy:
      fail-fast: true
      matrix:
        client: [JS, PY]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Set up python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Ubuntu packages
      run: |
        set -euo pipefail
        sudo apt-get update -y
        sudo apt-get install -y libpq-dev postgresql-client wait-for-it
    - name: Run webservices tests
      run: |
        set -euo pipefail
        mkdir -p ${HOME}/.gradle
        cp config/ci/gradle.properties ${HOME}/.gradle
        ./config/ci/init-solr.sh ${GITHUB_WORKSPACE}
        ./config/ci/init.sh ${GITHUB_WORKSPACE} $(which python3) ws ${{ matrix.client }} http://localhost:8080/intermine-demo
        ./config/ci/run.sh ${GITHUB_WORKSPACE} $(which python3) ws ${{ matrix.client }} http://localhost:8080/intermine-demo
