name: InterMine CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    services:
      # Label used to access the service container
      postgres:
        image: postgres:11
        # Provide the password for postgres
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    env:
      TESTMODEL_URL: http://localhost:8080/intermine-demo
      TESTMODEL_PATH: intermine-demo
      TERM: dumb
    strategy:
      fail-fast: false
      matrix:
        testSuite: [intermine, bio]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Set up python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'  
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libpq-dev postgresql-client
        sudo service postgresql start
    - name: Run unit tests
      env:
        TEST_SUITE: ${{ matrix.testSuite }} 
      run: ./config/ci/init.sh && ./config/ci/run.sh
  
  ws-tests:
    runs-on: ubuntu-latest
    
    services:
      # Label used to access the service container
      postgres:
        image: postgres:12
        # Provide the password for postgres
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    env:
      TESTMODEL_URL: http://localhost:8080/intermine-demo
      TESTMODEL_PATH: intermine-demo
      TERM: dumb
    strategy:
      fail-fast: false
      matrix:
        client: [JS, PY]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Set up python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'  
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libpq-dev postgresql-client
        sudo service postgresql start
    - name: Run webservices tests
      env:
        TEST_SUITE: ws
        CLIENT: ${{ matrix.client }}  
      run: ./config/ci/init-solr.sh && ./config/ci/init.sh && ./config/ci/run.sh


